# THIS EXAMPLE INSTALLS A HELM CHART FROM A GIT REPOSITORY

kind: Namespace
apiVersion: v1
metadata:
  name: hello-world
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd # All resources, including Application and AppProject specs, have to be installed in the Argo CD namespace (by default argocd).
spec:
  project: default
  source:
    repoURL: https://github.com/ricardofukuda/helm-hello-world.git
    targetRevision: master
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-world