# THIS EXAMPLE INSTALLS A HELM CHART FROM A BITNAMI REPOSITORY

kind: Namespace
apiVersion: v1
metadata:
  name: apache
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apache
  namespace: argocd # All resources, including Application and AppProject specs, have to be installed in the Argo CD namespace (by default argocd).
spec:
  project: default
  source:
    chart: apache
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 9.0.2
    helm:
      releaseName: apache
  destination:
    server: https://kubernetes.default.svc
    namespace: apache